### ISSUE TITLE
Running while no one is on

### ISSUE THREAD

**Issue by remotevase** [Inactive-to-Reactive/SurvivalGamesV4#4]
DO NOT DELETE THIS!!!!!

Before you make an issue, make sure your issue matches the criteria below
Once the issue is submitted, PLEASE TICK THE CHECKBOXES BY CLICKING ON THEM! 
- [X] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [X] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [X] This issue is written in your native language for maximal clarity
- [X] This issue does not have abbreveations. Abbreviations make it not understandable.
- [X] This issue is for SurvivalGamesV3, and not any other plugin.
- [X] This is not a suggestion, but an actual issue<br> <br>

NOTE: If it is a suggestion, title it [SUGGESTION] ______

If all the checkboxes are checked, congratulations! Fill out the fields below
! = required

! <--STATE SERVER PROVIDER HERE (EG POCKETMINE, IMAGICALMINE, GENYSIS etc)-->

! <--STATE ISSUE HERE-->When someone logs out and theres only one player. The sign says its running and no one can join :/

<--PUT ANY CONSOLE ERRORS HERE-->

<--IF CRASH DUMPS ARE AVAILABLE, PASTE THE ENTIRE FILE'S CONTENTS HERE-->

**Comment by bbka123** [comment]
Here are some questions.

**Comment by bbka123** [comment]
Unable to setrank
And when the player leaves the game and the server, the backpack is not empty.

**Comment by Mike4l6** [comment]
Make a new issue don't post it here

**Comment by Mike4l6** [comment]
ITS FIXED OH YEA

**Comment by Taki21** [comment]
Lel it was stupid back slash missing xD
