### ISSUE TITLE
SGV4: The Customizable Update (TODO Before SGV5)

### ISSUE THREAD

**Issue by Taki21** [Inactive-to-Reactive/SurvivalGamesV4#7]
# To Do List for SurvivalGamesV4 

## SurvivalGamesV4: The Customizable Update!

- [ ] Stablize Random Chest Generation
     - [ ] Tested <br>
- [ ] Better Random Items Appearances in Chest during SG Game
     - [ ] Tested <br>
- [ ] Option whether or not to Clear Inventory After Game
     - [ ] Tested <br>
- [ ] Option to Keep Kit Items and Effects for next SG Game
     - [ ] Tested <br>
- [ ] Option for a double "Death Match"
     - [ ] Tested <br>
- [ ] Option if want random items in chest without having to choose items in Config
     - [ ] Tested <br>
- [ ] Better Sign Format
     - [ ] Tested <br>
- [ ] Option for VIP+ to have access to any kits with a tap of a sign (Changing Kits)
     - [ ] Tested <br>
- [x] More Kits
     - [x] Tested <br>
- [ ] Fix the rank prefix in Chat
     - [ ] Tested <br>
- [x] Option to Customize the SG Prefix (Only in Chat)
     - [ ] Tested <br>
- [ ] Boost Performance
     - [ ] Tested <br>
- [ ] Fix Multiple Bugs
     - [ ] Tested <br>
- [ ] Add: "Player Joined The Match" Message, allow customization on that
     - [ ] Tested <br>

**Comment by Taki21** [comment]
@remotevase

**Comment by remotevase** [comment]
Good

**Comment by Taki21** [comment]
Lots of stuff xD

**Comment by remotevase** [comment]
Aw heck yea, I'd say too much, but whatevs, it **is** a huge update, after all!

**Comment by Taki21** [comment]
Lel

**Comment by remotevase** [comment]
Edited main post and title

**Comment by Taki21** [comment]
ok

**Comment by remotevase** [comment]
Naw, we dont want a title that long. Indestructible update is already in the issue title

**Comment by Taki21** [comment]
Make People Interested

**Comment by Taki21** [comment]
: )

**Comment by remotevase** [comment]
I'm gonna get right to work tomorrow. First, im gonna change all the numbers to V4, then im gonna add the sg prefix customization

**Comment by Taki21** [comment]
ok ill do kits

**Comment by Taki21** [comment]
@ImagicalGamer 
HELP US! lel

**Comment by Taki21** [comment]
@Mike4I6

**Comment by remotevase** [comment]
@Taki21 no, should be V5 b/c V5 has less TODO, so it can also be the user feedback update

**Comment by remotevase** [comment]
updated first post to include "test it"

**Comment by Mike4l6** [comment]
Heres another suggestion what if you had another way of going into the match, after you tap the sign you want players to join at there will be a message that will say /join [SG INSERT MAP HERE] , and you can insert the map and will only contain 10(or whatever) and you can do /sg list , for all of the /join sgmap commands :D

**Comment by Taki21** [comment]
sounds good ...... but the code i have no clue where to start that

**Comment by remotevase** [comment]
See
https://github.com/Inactive-to-Reactive/SurvivalGamesV4/wiki/All-SG-To-Do-Lists
and 
https://github.com/Inactive-to-Reactive/SurvivalGamesV4/issues/11
