### ISSUE TITLE
SGV5: The Statistical Update (TODO Before SGV6)

### ISSUE THREAD

**Issue by Taki21** [Inactive-to-Reactive/SurvivalGamesV4#8]
# Survival Games V5 - The Statistical Update!
 
### This means obviously more statistics, and also mow features based on user feedback

- [ ] Add Statistics of Kill : Death Ratio with a Command
     - [ ] Tested <br>
- [ ] Option to enable prefix to Show Rank (1st, 2nd, etc.) and/or K : D Ratio
     - [ ] Tested <br>
- [ ] Add Statistical Signs Showing People's Status + Leaderboards
     - [ ] Tested <br>
- [ ] See the Leaderboards with a quick command and see how you and you're friends are doing!
     - [ ] Tested<br>
- [ ] Message + Text Fixes
     - [ ] Tested <br>
- [ ] Bug Fixes
     - [ ] Tested <br>
- [ ] When someone dies, give them the choice to be in spectator mode. If the player wants to join another match and leave spectator do a command like /leave
     - [ ] Tested <br>

**Comment by Taki21** [comment]
@remotevase

**Comment by remotevase** [comment]
Oh, goodness taki! Stick with V4 for now; we got a lot to do!

**Comment by Taki21** [comment]
for future xD

**Comment by Mike4l6** [comment]
When someone dies put them to spectator mode (which theres already a plugin with) BUT, after the game finishes all the players come and see 1st,2nd,and 3rd players in a stack thing you know, if the player wants to join another match and leave spectator do a command like /leave

**Comment by remotevase** [comment]
Oh, good idea! Yeah, that will be in V5

**Comment by remotevase** [comment]
@Mike4l6 added to the list!

**Comment by Mike4l6** [comment]
Thanks :D Hope theres gonna be a good output

**Comment by remotevase** [comment]
Yup!

**Comment by Taki21** [comment]
Hmm, Maybe we can put dis in SGV4 put it more sooner!

**Comment by remotevase** [comment]
No, but V5 has less TODO so we put it in here

**Comment by remotevase** [comment]
Edited first post to include "Test it"

**Comment by Taki21** [comment]
Majority

**Comment by remotevase** [comment]
Kk

**Comment by remotevase** [comment]
See
https://github.com/Inactive-to-Reactive/SurvivalGamesV4/wiki/All-SG-To-Do-Lists
